server:
  port: 8848

spring:
  jpa:
    hibernate:
      hibernate.ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
  application:
    name: @artifactId@
  sql:
    init:
      schema-locations: classpath:books.sql
      platform: h2

