
drop table book if exists;
CREATE TABLE book (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(100) NOT NULL,
                      author VARCHAR(100),
                      intro VARCHAR(1000),
                      pub_year INT,
                      isbn VARCHAR(100) UNIQUE
);


INSERT INTO book (id, name, author, intro, pub_year, isbn) VALUES
(2, 'test123', '', '', 0, ''),
(6, '略略略', '空气', '弄哭', 2012, '空桶');

-- END TABLE book

